### ISSUE TITLE
Links to company details

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#12]
Extract data on company details (available in date.gov.md) and link them to relevant section in the portal.

Need to send manual steps we do for updates to Mirelle and need to look into the possibility of simplifying the process through the interface.

**Comment by mireille-raad** [comment]
I checked with team and it is possible to assign someone in PPA to manually maintain this task.
Can we do one of the following:

**option 1**
Either create an "import file" option in the dashboard where someone uploads a csv file and it gets imported to the system - the conflicts or rows that need a decision from a human are shown in a table, with buttons of the different action needed (maybe discard, edit and insert, replace etc..)

**option 2**
Create a detailed manual of the instructions needed to import company data directly into the database. It could be running a script, uploading a file etc.

Let me know if you think we have other options.

**Comment by bezunakarmi** [comment]
We have implemented upload company details file component. Now, a user can upload a company detail excel file and import it to database with necessary cleaning of name.
![screen shot 2017-05-25 at 1 59 33 pm](https://cloud.githubusercontent.com/assets/12218329/26442083/c14129a2-4152-11e7-89c5-ed3ab17792b6.png)

**Comment by mireille-raad** [comment]
ouww... looks fancy :) 

can we edit the text to be:
"Please upload the company details excel from website.com"

Since I never knew about where the website it, it will be handy if we just have the website link in the text (because at some point some admin in PPA or someone won't remember the link and they'd wanna ask us about it)

Also, I remember we said we would have 2 uploads, one for blacklists and one for this... correct ?

**Comment by bezunakarmi** [comment]
For the Blacklist data, http://tender.gov.md/ is currently un-accessible, we will work on blacklist data  once its fixed.

**Comment by mireille-raad** [comment]
- [X] upload functionality for uploading new company details added
- [X] link to where to get this data is added
- [X] showing the last import is added

Do you wanna close this issue and open a new one for creating upload functionality for blacklisted contractors?

**Comment by anjesh** [comment]
Thanks @dc-coder. Create a new issue to handle blacklisted contractors once tenders site is working https://github.com/younginnovations/opencontracting-moldova/issues/54
