### ISSUE TITLE
Displaying feedback / complaints received by PPA 

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#15]
Include explanation of “Appeals” section as a popup

Add a disclaimer that the information on the complaints covers the period until May 1, 2016 as from this date onward - complaints are handled by a separate complaint body

**Comment by bezunakarmi** [comment]
@anjhero we will need design on how to display this in tender's detail page.

**Comment by anjesh** [comment]
We just need to have some icon near Appeal and show the above disclaimer in popup when clicked.

http://moldova-demo.yipl.com.np/tenders/9032986

![image](https://cloud.githubusercontent.com/assets/120488/24595573/79e1d526-1857-11e7-8e6e-55537fa89cf9.png)

If @anjhero could take a quick look and give ideas, much better. Thanks.

**Comment by bezunakarmi** [comment]
This has been done. Please do check.
http://moldova-demo.yipl.com.np/tenders/9032986
![screen shot 2017-04-26 at 3 20 35 pm](https://cloud.githubusercontent.com/assets/12218329/25428280/190ce81c-2a95-11e7-8afb-2879b5451b2d.png)
