### ISSUE TITLE
Comment feedback moderation feature.

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#16]
- [ ] Feature to view comments.
- [ ] Remove comments.
- [ ] add images.files in comment.

**Comment by mireille-raad** [comment]
I checked this feature and so far the hide/show comment works :D 

If you click on the row, it takes to the contract page.... so, @anjesh  can we mark this issue as closed???? is there anything else you wanted to add ?

**Comment by anjesh** [comment]
Yes, we can close this, but there was feedback on adding images in the comment as well. Should we just ignore that one? It's not that important in my opinion. What do you say? @dc-coder

**Comment by mireille-raad** [comment]
Yeah... can close it.

Adding the image in the preview of the row might turn our tricky and a bit weird visually. Besides, people can click on the row and go to the comment.

Maybe if the comment is only an image, you can add a placeholder text saying that "user has uploaded an image, please click to view" ... something like that.

**Comment by anjesh** [comment]
Then i am closing this. Lets not complicate the feature with image addition then.
