### ISSUE TITLE
Cross browser compatibility

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#18]
The portal is displayed differently in different browsers (for example firefox)

**Comment by anjesh** [comment]
@isurajkc could you please have a look at the different browsers and post any issues if found here. Thanks.

**Comment by bezunakarmi** [comment]
The only issue found was placeholder not displaying for global search on header. This has been solved. I'm closing this issue for now. We can re-open this issue if any error found.
