### ISSUE TITLE
Data presentation: showing multiple years selection in the graphs

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#20]
Presenting data: It would be much better if the user can select periods. Because for example in 2015, the top contractor could not be listed in top 10. There is posibility of selecting year but is not clear: the info is for this year or until this year. And how to select for example period from 2015 to 2017?

**Comment by anjesh** [comment]
@dc-coder, what do you say? The chart in the homepage is not designed for multi-year but rather snapshot of one year only.

**Comment by mireille-raad** [comment]
i see the point of wanting start/end year for the graphs. is it super hard to change the graph to use between operator for year x and year y instead of equals ?

**Comment by anjesh** [comment]
No it's not super hard :) Just need to have two years side by side instead of one year as of now. You think this is good to go. @dc-coder

**Comment by mireille-raad** [comment]
yeah, good to go if you can have the 2 years next to each other.

An alternative to 2 years next to each other is a date range slider, if you like those and if you think they are less clutter, feel free to use them ;p --- i have no preference, just a suggestion.

**Comment by bezunakarmi** [comment]
The year range slider has been added to the portal. Please do have a look.
![screen shot 2017-05-12 at 9 36 30 am](https://cloud.githubusercontent.com/assets/12218329/25981738/acbe1816-36f6-11e7-8ffc-94e738179984.png)
