### ISSUE TITLE
Filter and Data Issues

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#21]
In “Agencies”. 
List: sorting by columns not working
Tried to open a line -- no charts (Fetching data...)
Incorrect data: Example
AGENŢIA PENTRU OCUPAREA FORŢEI DE MUNCĂ A MUNICIPIULUI CHIŞINĂU
Has 3 contracts in sum of 359000. But when details are opened we can see 9 contracts! Which info is correct?

Pagination of lists doesn’t work properly and it seems incorrectly. It throws an error when you try to access the last page. And if we have more than 2,000 pages how to access the 1950th page? One-by-one?

Search do not work properly. For example in the “Agencies” I’ve tried to search “Publice”.
On http://opencontracting.date.gov.md -- no results
On http://moldova-demo.yipl.com.np -- a list of irrelevant results. And 27 pages of results. But only 3 pages with data.

And user must know how many lines he have received as result of searcchhing.

Trying to search from the right corner “Agency”. Result: Whoops, looks like something went wrong.
But on http://opencontracting.date.gov.md I’ve receved one result but irrelevant. 
So whici platform is the right one? Whici should be tested??

**Comment by bezunakarmi** [comment]
These issues has been solved. please have a look.

**Comment by mireille-raad** [comment]
Here are some sorting done on the different columns... the numbes are not really sorting correctly.
![sort-tender](https://cloud.githubusercontent.com/assets/521705/24349372/7306135c-1311-11e7-9308-2fd30a037b9b.PNG)
![sort-contracts](https://cloud.githubusercontent.com/assets/521705/24349374/732b82c2-1311-11e7-81a6-9b2c21f92e92.PNG)
![contract-value](https://cloud.githubusercontent.com/assets/521705/24349375/732d3752-1311-11e7-85ce-85c240afba57.PNG)

Also for search, i tried searching for "academia" Here is the landing page  featuring a few rows with "academia", when i searched, i did not get them in the search results. could it be the case sensitivity?

![academia-no-search](https://cloud.githubusercontent.com/assets/521705/24349953/1d177e84-1313-11e7-9544-b8234be3159a.PNG)

![academia-search](https://cloud.githubusercontent.com/assets/521705/24349784/a6959aac-1312-11e7-9d8c-261ae5915406.PNG)

**Comment by bezunakarmi** [comment]
@dc-coder are you checking it on [moldova-demo](http://moldova-demo.yipl.com.np/procuring-agency) or [opencontracting.date.gov.md](http://opencontracting.date.gov.md/). Sorting is working correctly in moldova-demo site.
![screen shot 2017-03-27 at 4 48 28 pm](https://cloud.githubusercontent.com/assets/12218329/24353511/95d585f6-130d-11e7-93a5-205616fe59cf.png)
![screen shot 2017-03-27 at 4 48 48 pm](https://cloud.githubusercontent.com/assets/12218329/24353512/96610ed2-130d-11e7-9d1b-2ae418555834.png)

For the search result, we are onto it.

**Comment by mireille-raad** [comment]
I just checked on mobile and the sorting seems to work. Maybe it was cache.

Any idea about the search results?

**Comment by bezunakarmi** [comment]
The search result has also been fixed. Please have a look.
![screen shot 2017-03-27 at 6 06 25 pm](https://cloud.githubusercontent.com/assets/12218329/24356080/346a0a48-1318-11e7-84a9-3e8c8d3c9a12.png)

**Comment by mireille-raad** [comment]
:D the search and sorting are working properly :) thanks!

i tried search on mobile previously but it did not work, do you mind checking that!

Now i noticed that the column "contracts" - all values showing there are "1" - In the previous screenshot it is not the case, so anything happened to the values there?

One of the things raised in the tickets by bezunakarmi  is the fact that number of contract in this table does not matchup the number of contract in the details page... so it would be great to verify the summaries/values shown here.

**Comment by mireille-raad** [comment]
still same issue with one contract only showing for all entities. any idea if this is a glitch?

**Comment by bezunakarmi** [comment]
@dc-coder we are looking into this issue.

**Comment by bezunakarmi** [comment]
The issue with the agencies lists has been fixed. Please have a look.
![screen shot 2017-04-05 at 10 14 25 am](https://cloud.githubusercontent.com/assets/12218329/24689791/c27165b2-19e8-11e7-8b07-25ef0e2fd4d6.png)

**Comment by mireille-raad** [comment]
Mobile search is also working :D :+1: 

Should we add how many results the search included and we are done with this ticket ?

**Comment by bezunakarmi** [comment]
Sure, showing number of search result  will be more informative.

**Comment by anjesh** [comment]
I am closing this issue as showing results count will be taken care based on the UI as discussed in this issue https://github.com/younginnovations/opencontracting-moldova/issues/8
