### ISSUE TITLE
Visual interface to see API updates 

### ISSUE THREAD

**Issue by anjesh** [younginnovations/opencontracting-moldova#22]
Need to put some visual snapshot of the interface to see how data was pulled, when, no of records, troubleshooting steps, buttons to restart processes, instructions to give to IT, different levels of troubleshooting etc.

**Comment by anjesh** [comment]
@anjhero need some quick UI on how this might look like based on [this doc](https://docs.google.com/document/d/16nXJiZslEFmWBcG1Uq2bbC8N6kn99Mp5-YV1475oY-4/edit?ts=58c94b6f)

cc @bezunakarmi

**Comment by anjhero** [comment]
Hi all, I've pulled together a design based on the description given above. Basically, this screen will act as a Dashboard page that appears after an authenticated user logs in. Please take a look:
![dashboard](https://cloud.githubusercontent.com/assets/528549/24282396/4c616102-1087-11e7-8769-8bdf2f93357c.png)

**Comment by mireille-raad** [comment]
@anjesh  Can you push this code to the demo site and share the link with Elena and tin ?

**Comment by timilsinabishal** [comment]
@dc-coder please see http://moldova-demo.yipl.com.np/dashboard .Currently this page provides minimal info about api updates and more functionalities will be added later.

**Comment by mireille-raad** [comment]
how to get past login? is there a way you can register the user mraad@worldbank.org ? (should i receive automated email with login?)

**Comment by bezunakarmi** [comment]
@dc-coder we don't have register feature for admin login. I'll send you an email with the login credentials.

**Comment by mireille-raad** [comment]
looks great!! are you doing the actual coding of this screen now?

**Comment by anjesh** [comment]
Yes @dc-coder

**Comment by mireille-raad** [comment]
Good luck!

**Comment by mireille-raad** [comment]
the button "import data now" disappeared ;p is it still gonna be coded/added ?

**Comment by bezunakarmi** [comment]
We are still working on its functionalities. But the button can be added for now.

**Comment by mireille-raad** [comment]
any update on the automatic data synch and import button?

**Comment by bezunakarmi** [comment]
Manually importing data from API has been completed. Now, we can click on the "Import data now" button to import data manually. Also, the "View assesment data" link will download a csv file where a level of data assesment has been done. Please do have a look.
![screen shot 2017-05-12 at 9 51 21 am](https://cloud.githubusercontent.com/assets/12218329/25982062/07be6f84-36f9-11e7-8ced-873129bf1767.png)

**Comment by mireille-raad** [comment]
I tried to import and the button says "importing" even after one hour of clicking it.

Is there a way to know once the import has been done? or any progress bar? or count of rows imported so far?

Is this re-importing all the data or just the new one?

(can we re-open this issue until it is tested?)

**Comment by timilsinabishal** [comment]
@dc-coder The logs of the import can be seen [here](http://moldova-demo.yipl.com.np/import-status.txt). And for now we are re-importing all the data.

**Comment by anjesh** [comment]
Need to update the interface to include the "Contracts XLS" import button that will call the import and cleanup scripts. 

Also when the etenders import is going on, lets show the message "importing <with icon which gives the popup with the following info - Data import will take around 2-3 hours for completion. You may see the progress <link to log>log<link>"

**Comment by mireille-raad** [comment]
@timilsinabishal  thanks for sharing the log file.

Can we also make the log generate in reverse order ? (instead of appending at end... insert at beginning?)

(should we open different issues for those different things to keep your life easier and more organized?)

**Comment by timilsinabishal** [comment]
@dc-coder The logs are now shown in reverse order. And we have also added the company excel upload functionality. Please have a look. Yes keeping different issues will definitely make it easier.

**Comment by anjesh** [comment]
This can be closed as only blacklist contractors import functionality is remaining - will be addressed in a different issue https://github.com/younginnovations/opencontracting-moldova/issues/54

**Comment by mireille-raad** [comment]
Finally! thank you for all your hard work on this issue... this has not been easy. ;p
