### ISSUE TITLE
Period shows number instead of dates

### ISSUE THREAD

**Issue by anjesh** [younginnovations/opencontracting-moldova#28]
See the period below the tender title

http://moldova-demo.yipl.com.np/tenders/9032986

![image](https://cloud.githubusercontent.com/assets/120488/24595547/32fce15a-1857-11e7-9d00-532cc5fce1c6.png)

**Comment by bezunakarmi** [comment]
This issue has been fixed .Please have a look
http://moldova-demo.yipl.com.np/tenders/9032986
![screen shot 2017-04-03 at 2 42 12 pm](https://cloud.githubusercontent.com/assets/12218329/24602347/242e042c-187c-11e7-9619-06a9c686dc65.png)
