### ISSUE TITLE
Update Wiki documentation

### ISSUE THREAD

**Issue by anjesh** [younginnovations/opencontracting-moldova#29]
Wiki documentation https://github.com/younginnovations/opencontracting-moldova/wiki/user-manual needs to be updated as per new updated site.

**Comment by bezunakarmi** [comment]
Wiki docs has been updated, do have a look. Let us know if there any issues.

**Comment by anjesh** [comment]
@dc-coder please have a look at the updated wiki.

**Comment by mireille-raad** [comment]
excellent - reviewing and sharing with colleagues.

Is it ready for translation?

**Comment by mireille-raad** [comment]
can you embed the screencast playlist on the homepage of the wiki ? or can we have a page that says "video tutorial" ?

If you want, if you give me access to edit the wiki... I am happy to do that with colleagues here and not bug you about every single change. I can also upload any translation when done etc.
