### ISSUE TITLE
Blank buyer list in the home page advanced search

### ISSUE THREAD

**Issue by anjesh** [younginnovations/opencontracting-moldova#31]
http://moldova-demo.yipl.com.np/

![image](https://cloud.githubusercontent.com/assets/120488/24642608/30ffe376-1928-11e7-9c3d-d0d457b2e7c7.png)

**Comment by bezunakarmi** [comment]
This issue has been solved. Also search filter has been fixed, previously result didn't validated the data for search result. Please do have a look.

![screen shot 2017-04-05 at 4 55 48 pm](https://cloud.githubusercontent.com/assets/12218329/24703362/a44ca2ba-1a22-11e7-8842-88bb62519032.png)
