### ISSUE TITLE
Procurement method value is incorrect

### ISSUE THREAD

**Issue by anjesh** [younginnovations/opencontracting-moldova#34]
It's showing the registration agency for PE.

![image](https://cloud.githubusercontent.com/assets/120488/24786915/a629a264-1b84-11e7-87d9-6e20ef02bf74.png)

**Comment by bezunakarmi** [comment]
This has been solved.
![screen shot 2017-04-07 at 4 30 37 pm](https://cloud.githubusercontent.com/assets/12218329/24797120/9625541e-1baf-11e7-9d7f-c86d1894722a.png)
