### ISSUE TITLE
Prepare a list of strings/labels for translation

### ISSUE THREAD

**Issue by anjesh** [younginnovations/opencontracting-moldova#4]

**Comment by mireille-raad** [comment]
Do you want to use something like https://www.transifex.com to manage the translation?

**Comment by anjesh** [comment]
That looks good, but for now, we have created a google spreadsheet where the translation could be entered https://docs.google.com/spreadsheets/d/1IhecfeYcUC55zNzYckC6qGTkd4XisFkNj_8AzeaEf5k/edit?ts=5760ed5f#gid=0

**Comment by mireille-raad** [comment]
Excellent!! Who is taking the lead on the actual translation? do you need us to send this to some translators or share with PPA? If this is 100% done, wanna close the issue?

**Comment by anjesh** [comment]
The list is shared and translated by PPA.

**Comment by mireille-raad** [comment]
I just saw the translation drop down on the website :D :D  looks excellent!

I also started a Romanian version of OCDS - i'll copy what PPA translated from the google doc!
