### ISSUE TITLE
Managing usernames and passwords for the Dashboard

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#48]
So far, i've been able to login because i was given a username and password.

Is there a way to add/edit/delete other users? (generic user management?)

**Comment by anjesh** [comment]
@dc-coder, could you give us the email addresses for PPA and worldbank so that we will create those users directly in the db for now? The generic user management isn't of a priority as we discussed earlier. Thanks.

**Comment by mireille-raad** [comment]
can we use  a username instead of an email? (emails might change or no longer be valid... so in the mind of people it is weird... multiple people here will be using the same login, so who's email is tied to account becomes tricky)... also from programming perspective... it is same thing... username or email.. it is just a string to match.

Can we have the following usernames:
- super-admin
- ppa-admin
- wb-admin
- comms-admin
- IT-admin

The users should be able to update their own passwords, so in theory, the passwords are not hard coded and we no longer have access to them... people can use something they can remember etc.

Maybe super-admin only, can update everyone's passwords in case someone forgot (it will also be a way to manage who has access to the backend by just changing the password and only giving the new one to specific people)
It will be useful for super admin username to have an email... if someone is trying to login and can't... a text shows and says please send an email to email-of-super-admin@something.com ... and like this you won't have to do a reset password mechanism (unless you think it is easy or already have code that you can re-use)

Let me know if this sounds like an ok strategy... it should be easy to implement without adding a whole module of user management. Did we leave any use cases out?

(I am running this by the team and getting their feedback as well.... let me know your thoughts first)

**Comment by bezunakarmi** [comment]
@dc-coder , we have implemented a simple user management system. Here the above-mentioned users are pre-inserted in the database. Also a seed file has been added, by which we can add these users on any machines.

All the users have been assigned with same password:
- superadmin : @-admin
- ppa-admin : @-admin
- wb-admin : @-admin
- comms-admin : @-admin
- IT-admin : @-admin

![screen shot 2017-06-12 at 3 25 46 pm](https://user-images.githubusercontent.com/12218329/27028257-ff4b0a9e-4f83-11e7-8d74-c364f16b19c2.png)

Also a interface where super-admin can change password of other users.
![screen shot 2017-06-12 at 3 25 59 pm](https://user-images.githubusercontent.com/12218329/27028313-29c497c2-4f84-11e7-9fbc-97f438d34335.png)

Also, super-admin can add a new user and activate/deactivate a user.
![screen shot 2017-06-12 at 3 26 24 pm](https://user-images.githubusercontent.com/12218329/27028358-4f6ac028-4f84-11e7-8785-b4d8d5d5648a.png)
![screen shot 2017-06-12 at 3 26 37 pm](https://user-images.githubusercontent.com/12218329/27028360-50582a66-4f84-11e7-8a02-9a59391a2db5.png)

We haven't implemented the mailing to super-admin feature yet. Could you provide us an email which can be used for super-admin?

Do have a look at it, and let us know if there is any other things that's need to be added.

**Comment by mireille-raad** [comment]
thanks a lot for the work put into this.

can the super admin just configure their own email? as this information might change over time. If you can save it somewhere in a database or in just a config file or a json... that would be enough.

I tried to login, but i am being asked for an email.... can you change the validation in the UI to no longer require an email?

<img width="1248" alt="screen shot 2017-06-12 at 10 17 36 am" src="https://user-images.githubusercontent.com/521705/27038257-7018371e-4f58-11e7-970f-9b7ffa2d47bf.png">

**Comment by bezunakarmi** [comment]
Surely, we can add a super-admin email in the config file or .env file.

We have deployed the changes in the demo site (http://moldova-demo.yipl.com.np), cause it is in the test phase. If its good to go, we will deploy it to the production site.

**Comment by mireille-raad** [comment]
I just checked the user management module and yes this works :)  let's close this issue.

I had a conversation with Anjesh a time ago about changing the DNS settings... I was under the impression that the demo = opencontracting.date.gov.md

This is a conversation for another issue tho
