### ISSUE TITLE
Blacklist companies import functionality

### ISSUE THREAD

**Issue by anjesh** [younginnovations/opencontracting-moldova#54]
The [visual status interface](https://github.com/younginnovations/opencontracting-moldova/issues/22) needs to have the import functionality for blacklist companies as well - it could be either excel upload or scrapping from tenders site. However http://tender.gov.md/ is not working since some time now to start working on this. 

The blacklist information is already available in the site now but we just need to have the button for pulling these updated blacklist information on a regular basis.

**Comment by mireille-raad** [comment]
yesterday i checked the website and today as well, both times it was working.
Is this what you are expecting to see ? 

![tender-moldova](https://cloud.githubusercontent.com/assets/521705/26637216/e001a8d2-45ec-11e7-8349-823dde2bcf7b.PNG)

Is this the black-listed page ? http://tender.gov.md/ro/lista-de-interdictie

**Comment by mireille-raad** [comment]
Let's make the import by uploading a file, not by scraping the data.

I noticed that http://tender.gov.md/ro/lista-de-interdictie doesn't have any file download... building a scraper might be too much effort from you for the task.... so if you add an import file like the previous one in the dashboard, it should be enough.

Someone will manually import these files.... we need to talk to PPA about making some of this data available in a more friendly machine readable format  like a csv or json.

**Comment by anjesh** [comment]
That's strange, we are seeing this 

![image](https://cloud.githubusercontent.com/assets/120488/26663535/10e7d2d2-46ab-11e7-9988-e82f562bcb7f.png)

**Comment by mireille-raad** [comment]
Add /ro to the end of your URL ... They seem to have implemented languages ... the / doesn't have anything... the /ro has the webpage...  Just a guess.

**Comment by mireille-raad** [comment]
You can also try http://etender.gov.md/blackList

**Comment by bezunakarmi** [comment]
@dc-coder Thanks for the link. We will get back to you with progress on this issue.

**Comment by mireille-raad** [comment]
any progress?

**Comment by timilsinabishal** [comment]
@dc-coder Blacklist import functionality is added to http://moldova-demo.yipl.com.np/dashboard .
 
![screenshot from 2017-06-09 11-34-02](https://user-images.githubusercontent.com/10270971/26962678-aaf3b44c-4d07-11e7-8f1e-c3c8a1b0706f.png)
See [blacklisted contractor](http://moldova-demo.yipl.com.np/contracts/contractor/DELMIX-PRIM%20S.R.L.) .

![screenshot from 2017-06-09 11-33-17](https://user-images.githubusercontent.com/10270971/26962677-aaf096ae-4d07-11e7-805b-e11b775e272a.png)

**Comment by mireille-raad** [comment]
Can you add a direct link to where the blacklist information can be found?

**Suggestion**
For the company data ... you have last import date.... do you think it makes sense to add the same information for the blacklist, can we have last import dates for the blacklisted companies as well ?

**Addition to "useful links" in the dashboard**
In useful links, can you add the two following links:
- default file format for blacklisted companies
- default file format for company details

Those links should just trigger a download of the empty excel sheets... it will be a good way to document how the files should look like. In case the files change, we have the default template people need to have.... or at least there is understanding that files need to have a certain format.

**Comment by mireille-raad** [comment]
I saw that the UI is updated for this... just a few pending items

- Please upload the blacklist excel from [here ](www.google.com) [add the from here section)
- The blacklist file has 6 columns, the link has 9 http://tender.gov.md/ro/lista-de-interdictie , is there any way to know which columns go where? excuse my ignorance, but for someone who doesn't speak the language, this is not straight forward.

**Comment by bezunakarmi** [comment]
We have added the line "Please upload the blacklist excel from here " to our UI. We are using http://etender.gov.md/blackList for blacklist names, as for columns we have uploaded a sample excel sheet how the columns needed to be arranged.(organization name column is mandatory.)
![image](https://user-images.githubusercontent.com/12218329/27326972-cfbfd29c-55cc-11e7-96fd-5026154cf25b.png)

Also, we have added a general IT troubleshooting guide link to the dashboard, which is linked to Wiki pages.
![image](https://user-images.githubusercontent.com/12218329/27327104-2eef8dde-55cd-11e7-84d3-f20a8324bd1d.png)

Lets close this issue for now. If there is anything else we can reopen the issue.
