### ISSUE TITLE
Site down - add a monitoring feature?

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#58]
So the site is down on http://opencontracting.date.gov.md 

Can you please restart services (troubleshoot) and send me list of instructions you used?

Is there an option to configure a server monitoring tool like "Monit" - it literally takes 15 mins to configure https://mmonit.com/monit/ (any other tool of your choice would of course be great as well)

Thx!

**Comment by timilsinabishal** [comment]
@dc-coder We have restarted the mongodb service to fix the problem. It was down due to memory issues.  We have been scheduling the data update every day and the size of data is huge. We think we need to increase the memory of our server.

**Comment by mireille-raad** [comment]
We are working on making available a monthly endpoint on the etenders json. Hopefully this will resolve the memory issue.

Do you think we can have any server monitoring tool that restarts mongo when it stops? or at least send an email notification when mongo is down for someone to restart it along with instructions?

**Comment by timilsinabishal** [comment]
@dc-coder We are working on monitoring and alerting feature for service disruptions. It would be easier for us if some port is opened on the server for this feature.

**Comment by mireille-raad** [comment]
Which port do you want open? 
Do you have any list that we can get someone to do? (ports to open, things to enable?)
Let me know and I will try to make it easier for you :)

**Comment by mireille-raad** [comment]
can i also have access to the server (ssh maybe) and the instructions you guys used to restart/troubleshoot? (we might have some meetings soon about the portal with some govt officials and I am horrified of the prospect of the site going down while we are there... and i need to make sure if something goes wrong, i can quickly restart/fix)
Can @anjesh  maybe email this? and configure a login for me?

**Comment by timilsinabishal** [comment]
@dc-coder Default port for monit is 2812 but any other port will also be fine. For the meantime, we are disabling nightly automatic import feature to avoid memory issue. You can use `mongod -f /etc/mongod.conf` to start mongodb in case mongodb is down. We believe there is ip-filtering in ssh access, so please contact to someone authorized personnel for server access.

**Comment by mireille-raad** [comment]
I am emailing with IT to get port 2812 open and will get back to you once it is configured

Do you mind adding somewhere in the wiki the how to start mongo, enable automatic import, restart web server etc.? (it might be handy for whoever takes on the maintenance of the server after this)

Thanks!

**Comment by timilsinabishal** [comment]
@dc-coder The port is still not available, so we have configured monit at url http://moldova-demo.yipl.com.np/monit/ .Also the email alert is added in case of changes in mongodb and nginx service. We will mail to you with required authentication credentials. Please have a look.

![screenshot from 2017-06-15 15-09-18](https://user-images.githubusercontent.com/10270971/27174704-ba44263c-51dc-11e7-8888-6fb41f04f889.png)

**Comment by mireille-raad** [comment]
thanks a ton :) 

Now i can have some piece of mind... my SSH access was just configured. will test it one home.

**Comment by mireille-raad** [comment]
--
