### ISSUE TITLE
Data table, ajax error

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#59]
On tender http://opencontracting.date.gov.md/tenders 

If you click next on the table, you get the following data table ajax error

<img width="586" alt="screen shot 2017-06-06 at 11 19 38 am" src="https://user-images.githubusercontent.com/521705/26836893-127400f0-4aaa-11e7-8e07-0bbc679d2620.png">

**Comment by timilsinabishal** [comment]
@dc-coder This issue is fixed please have a look.

**Comment by mireille-raad** [comment]
thanks!
