### ISSUE TITLE
pushing from moldova-demo.yipl.com.np to opencontracting.date.gov.md

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#61]
Hey...

just one question... i know the changes are now on moldova-demo ... i think of that as dev. server

recently we updated the IP of opencontracting.date.gov.md to be the same as moldova-demo

`Pinging opencontracting.date.gov.md [185.108.181.38] with 32 bytes of data:`
`Pinging moldova-demo.yipl.com.np [185.108.181.38] with 32 bytes of data:`

What is the process that you are using for pushing the dev changes to production? Can we push the changes you have done so far please?

**Comment by bezunakarmi** [comment]
@dc-coder ,

Moldova-demo and opencontracting.date.gov.md are on the same server but are hosted differently. We use the demo site to test thing if they are working on the server. Once the codes are tested and verified we deploy them to the production.

Yes, we can move the codes to the production.

**Comment by bezunakarmi** [comment]
We are now pushing the code to the production after it has been verified in demo. we have deployed the latest code to production.

**Comment by mireille-raad** [comment]
it looks like the production is not really working.

On **production** the login feature gives this

![err](https://user-images.githubusercontent.com/521705/27443780-339d500c-5742-11e7-9f88-e22ba1d23655.PNG)


On **demo**, the login to dashboard feature works

![working](https://user-images.githubusercontent.com/521705/27443765-2b77f972-5742-11e7-8488-1f8a37c3f0e9.PNG)

Grateful if you can double check this

**Comment by bezunakarmi** [comment]
We couldn't duplicate this error. It's working when we checked from our side.
![image](https://user-images.githubusercontent.com/12218329/27466279-2b748956-57f9-11e7-94ea-a8872c57b54d.png)

![image](https://user-images.githubusercontent.com/12218329/27466244-ea36b914-57f8-11e7-94ec-c388e8c15f18.png)

**Comment by mireille-raad** [comment]
I just checked... somehow it is working now.
