### ISSUE TITLE
csv for tender, add tender dates

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#64]
We received the following comment during the peer review of the portal.

> CVS data extractable through the date portal lacks dates in tenders

I thought this is worth addressing... in the [Download page]( http://opencontracting.date.gov.md/downloads) >  CSV for tender, can you please add the start and end dates ?

Those dates are showing on http://opencontracting.date.gov.md/tenders - it will be really useful for anyone downloading the data and trying to use it.

I hope it is a small tweak.

**Comment by timilsinabishal** [comment]
@dc-coder start and end dates are added to tenders csv. Please have a look.

**Comment by mireille-raad** [comment]
thanks!! double checked...
