### ISSUE TITLE
error 404 for http://opencontracting.date.gov.md/import-status.txt 

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#66]
http://opencontracting.date.gov.md/import-status.txt gives error 404. Grateful if you can fix

![screen shot 2017-06-24 at 4 12 44 pm](https://user-images.githubusercontent.com/521705/27511661-205eac40-58f8-11e7-803e-073c49e02737.png)

**Comment by timilsinabishal** [comment]
@dc-coder At the moment we are disabling manual/automatic import after memory issues as mentioned in #58 . So no import-status file is generated. We are working on different import process using monthly json and will re enable import after it is completed.

**Comment by mireille-raad** [comment]
oh ok.. thanks for letting me know :) 

We are presenting the platform tomorrow... do you think the edit to the python script would be done? is it too complicated? does it go beyond getting the month from the system and add it to the url being imported?

If it is too complicated, can we maybe re-enable the import functionality temporarily?

**Comment by timilsinabishal** [comment]
@dc-coder We may not be able to complete the edit to python script by tomorrow as we need to do proper testing and validate data after. As for enabling import functionality, we will run import to get latest data, and disable it. You can tell that import functionality is disabled due to memory issues and to  upgrade the server.

**Comment by mireille-raad** [comment]
agree on need to do a good testing once and for all :) 

if you can run the import to get the latest data and then disable... that would be great and more than what we need.

thanks!

**Comment by timilsinabishal** [comment]
@dc-coder We have imported the latest data. Please have a look.

**Comment by mireille-raad** [comment]
Thanks! feel free to close this issue since it is the same as the API update (issue https://github.com/younginnovations/opencontracting-moldova/issues/7)

I checked the data and was able to see it in the table on the homepage.

![screen shot 2017-06-26 at 8 53 48 am](https://user-images.githubusercontent.com/521705/27540117-fe436f6e-5a4c-11e7-950d-21bd29b6a3e1.png)

Do you think you can make the default sort order of that table by most recent as a default? when page loads it shows data in 2012... it might be more relevant to show the most recent and should be a small tweak in the code.

**Comment by timilsinabishal** [comment]
@dc-coder The default sort is changed to show most recent contract. Please have a look.
