### ISSUE TITLE
comments login with google account not working

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#67]
trying to login with google to leave a comment gives error
![screen shot 2017-06-27 at 4 55 02 am](https://user-images.githubusercontent.com/521705/27580251-0d982526-5af8-11e7-8b27-564932ad0c34.png)

**Comment by timilsinabishal** [comment]
@dc-coder Google sign-on works now. However we are working in facebook login.

**Comment by mireille-raad** [comment]
just commented with my google account, thanks for fixing!

quick question: if an admin wants to reply to a user comment, now i am getting this pop-up

![object-object](https://user-images.githubusercontent.com/521705/27623931-71c6de80-5be7-11e7-8070-5644b3bc89d6.PNG)

should we fix it? or maybe disable the comment feature for admin?

**Comment by bezunakarmi** [comment]
The admin comment has been enabled. Also, Facebook login has been fixed. Please do have a look and let us know if there are any issues.
