### ISSUE TITLE
error 404 on Importing company details.

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#68]
When Importing company details, after uploading the excel file, I try to check status of the import. Get 404 error

![importing-company-status](https://user-images.githubusercontent.com/521705/27623205-f7970db8-5be3-11e7-9f0c-1a392686e942.PNG)

**Comment by timilsinabishal** [comment]
@dc-coder Just uploaded company excel in opencontracting.date.gov.md. Everything was working fine and company-import file was generated as well. I checked the demo site and company data was updated today. Are you sure you were uploading to production site.

**Comment by mireille-raad** [comment]
Let me re-test... it was production... i now make sure i keep the url in the screenshot as a self reminder or where it is.
