### ISSUE TITLE
Confusing user interface after black list import

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#69]
The user interface while uploading a blacklisted company is a bit confusing. Anything we can do to simplify this? It should be just changing the visibility of some labels.

![black-list-ui](https://user-images.githubusercontent.com/521705/27623295-7ce4bcfe-5be4-11e7-9d36-55be4ccb88de.PNG)

Here is my suggestion, after the file has finished uploading successfully, can we hide the "not imported" (which i am assuming shows at the progress level) and we can clear the name of the file.

**Comment by bezunakarmi** [comment]
Thanks for pointing it out. We will look into it and will let you know once it's done.

**Comment by bezunakarmi** [comment]
This issue has been attended. Please do have a look.
