### ISSUE TITLE
error 404 for monit dashboard

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#70]
Monit is configured to run on demo

![monit-yipl](https://user-images.githubusercontent.com/521705/27623648-0c315ba0-5be6-11e7-8e4f-beb95917d938.PNG)

Here is the error 404 screenshot on opencontracting.date.gov.md

![monit-gov md](https://user-images.githubusercontent.com/521705/27623653-1196c800-5be6-11e7-9003-3c583037b1ca.PNG)

Can we fix the config of the url?

**Comment by timilsinabishal** [comment]
@dc-coder Monit is configured on production too. Please have a look.

**Comment by mireille-raad** [comment]
Yap! working now! thanks a ton
![monit-gov md](https://user-images.githubusercontent.com/521705/27636078-74937a08-5c12-11e7-96c2-e406f56ac465.PNG)
