### ISSUE TITLE
Monit the faithful employee failed today

### ISSUE THREAD

**Issue by mireille-raad** [younginnovations/opencontracting-moldova#76]
Monit has been doing a great job keeping the site running. I frequently receive alert emails.

But today it seems like there is an odd error. I appreciate if you can take a look and restart mongod

![screen shot 2017-08-09 at 6 54 16 am](https://user-images.githubusercontent.com/521705/29105138-8a351718-7cd3-11e7-8b05-46c68a75793e.png)

I will also request a bigger server size ... please let me know what specs increase would be ideal.

**Comment by bezunakarmi** [comment]
Mongo service has been restarted. This occurred due to unexpected shutdown of the mongo server.

**Comment by mireille-raad** [comment]
thanks a lot :)
