### ISSUE TITLE
Setting Wiki Pages

### ISSUE THREAD

**Issue by bezunakarmi** [younginnovations/opencontracting-moldova#9]
Different pages will be added to the portal aimed at informing and training people on use of the portal.

- [x] Icon is not very visible 
- [x] We need to compile these into a single html page / pdf document within the portal
- [ ] Some files in github were not downloadable (need to follow up separately )

**Comment by anjesh** [comment]
> Why a such section doesn't exist on the portal? It is a question of comfortability

Because it's easy to create pages and edit in wiki when we are developing and updating. Once the content is finalized, these could be moved to a separate page in the portal.

**Comment by bezunakarmi** [comment]
New page for help has been added in the portal. Wiki pages have been added to portal. Please have a look at http://moldova-demo.yipl.com.np/help/

**Comment by mireille-raad** [comment]
there is an error on the link. while you work on fixing it, if you have a working local copy, can you share how the screens look like? email to tin, elena and mireille.

Which process did you end up using... i am curious to know.

**Comment by timilsinabishal** [comment]
The link for the help pages have been fixed. As for process, we are rendering github wiki markdown files to html as it eases updating content and synchronize wiki.
![wiki](https://cloud.githubusercontent.com/assets/10270971/24340209/307cff14-12d0-11e7-9869-74db10d0ab9a.png)
![exploring](https://cloud.githubusercontent.com/assets/10270971/24340216/37c1a324-12d0-11e7-8b04-d56dd1864b4b.png)

**Comment by mireille-raad** [comment]
thanks for fixing the link... 

Can we improve a little bit the look and feel of the landing page of the wiki? We wanted to add a playlist of the screen casts there ... so maybe you can include a youtube playlist there.

Also, does the wiki have translation.

**Comment by timilsinabishal** [comment]
@dc-coder The landing page of wiki uses [User-manual](https://github.com/younginnovations/opencontracting-moldova/wiki/user-manual), so we can edit this page to modify its contents. And currently the wiki is only available in English and needs translation for Romanian language.

**Comment by mireille-raad** [comment]
@timilsinabishal  should i follow up on the translation? any idea who is doing it? is the wiki's text final?

**Comment by bezunakarmi** [comment]
@dc-coder the wiki currently explains about live version of the portal. We are working on updating the wiki text for the updates (changes) that has been made to the portal.

**Comment by anjesh** [comment]
@dc-coder wiki text is not final as we are still updating the UI. We will update the text and screenshots in wiki once the UI is final and approved.

**Comment by anjesh** [comment]
@bezunakarmi could you please make sure that the icons are displayed for wiki? We can close this issue after that. As for finalisation of  text, we will update the wiki once the UI is finalized and completed. The wiki content updates will be covered in this issue https://github.com/younginnovations/opencontracting-moldova/issues/29

**Comment by bezunakarmi** [comment]
Wiki link icon has been added.
![screen shot 2017-05-22 at 1 58 10 pm](https://cloud.githubusercontent.com/assets/12218329/26298414/ed9424cc-3ef6-11e7-9835-9678bf348a6d.png)

**Comment by mireille-raad** [comment]
sorry to  resurrect this issue... but the wiki page/html on the portal is not working (do you mind re-opening so we are not discussing a closed issued)

http://opencontracting.date.gov.md/help
http://opencontracting.date.gov.md/help/agencies

Are the html pages supposed to be automatic generation from the wiki? If not, can the wiki have a wiki section on this ;p so, in case wiki is updated in the future once the github repo is passed back to PPA... we can make sure someone can do those steps.

**Comment by timilsinabishal** [comment]
@dc-coder The wiki page have been fixed . And yes the wiki page is automatically generated from github wiki.


![screenshot from 2017-06-01 09-39-33](https://cloud.githubusercontent.com/assets/10270971/26664148/12d91336-46af-11e7-90f8-60748a40d953.png)
